/**
 * Static mapping from FHIR R4 choice element paths (e.g. `'Observation.value[x]'`)
 * to their allowed data type names. Sourced from `https://hl7.org/fhir/R4/choice-elements.json`.
 *
 * @remarks
 * The wildcard `'*'` key lists every data type that can appear in an
 * unconstrained choice element (e.g. `Task.input.value[x]`). Used at
 * build time to derive typed union schemas via {@link DatatypeChoice}.
 */
const FhirR4ChoiceElements = {
  '*': [
    // Primitive Types
    'base64Binary',
    'boolean',
    'canonical',
    'code',
    'date',
    'dateTime',
    'decimal',
    'id',
    'instant',
    'integer',
    'markdown',
    'oid',
    'positiveInt',
    'string',
    'time',
    'unsignedInt',
    'uri',
    'url',
    'uuid',
    // Data Types
    'Address',
    'Age',
    'Annotation',
    'Attachment',
    'CodeableConcept',
    'Coding',
    'ContactPoint',
    'Count',
    'Distance',
    'Duration',
    'HumanName',
    'Identifier',
    'Money',
    'Period',
    'Quantity',
    'Range',
    'Ratio',
    'Reference',
    'SampledData',
    'Signature',
    'SimpleQuantity',
    'Timing',
    'MetaDataTypes',
    'ContactDetail',
    'Contributor',
    'DataRequirement',
    'Expression',
    'ParameterDefinition',
    'RelatedArtifact',
    'TriggerDefinition',
    'UsageContext',
    // Special Types
    'Dosage',
    'Meta',
  ],
  'ActivityDefinition.product[x]': ['Reference', 'CodeableConcept'],
  'ActivityDefinition.subject[x]': ['CodeableConcept', 'Reference'],
  'ActivityDefinition.timing[x]': ['Timing', 'dateTime', 'Age', 'Period', 'Range', 'Duration'],
  'AllergyIntolerance.onset[x]': ['dateTime', 'Age', 'Period', 'Range', 'string'],
  'Annotation.author[x]': ['Reference', 'string'],
  'AuditEvent.entity.detail.value[x]': ['string', 'base64Binary'],
  'BiologicallyDerivedProduct.collection.collected[x]': ['dateTime', 'Period'],
  'BiologicallyDerivedProduct.manipulation.time[x]': ['dateTime', 'Period'],
  'BiologicallyDerivedProduct.processing.time[x]': ['dateTime', 'Period'],
  'CarePlan.activity.detail.product[x]': ['CodeableConcept', 'Reference'],
  'CarePlan.activity.detail.scheduled[x]': ['Timing', 'Period', 'string'],
  'ChargeItem.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'ChargeItem.product[x]': ['Reference', 'CodeableConcept'],
  'Claim.accident.location[x]': ['Address', 'Reference'],
  'Claim.diagnosis.diagnosis[x]': ['CodeableConcept', 'Reference'],
  'Claim.item.location[x]': ['CodeableConcept', 'Address', 'Reference'],
  'Claim.item.serviced[x]': ['date', 'Period'],
  'Claim.procedure.procedure[x]': ['CodeableConcept', 'Reference'],
  'Claim.supportingInfo.timing[x]': ['date', 'Period'],
  'Claim.supportingInfo.value[x]': ['boolean', 'string', 'Quantity', 'Attachment', 'Reference'],
  'ClaimResponse.addItem.location[x]': ['CodeableConcept', 'Address', 'Reference'],
  'ClaimResponse.addItem.serviced[x]': ['date', 'Period'],
  'ClinicalImpression.effective[x]': ['dateTime', 'Period'],
  'CodeSystem.concept.property.value[x]': [
    'code',
    'Coding',
    'string',
    'integer',
    'boolean',
    'dateTime',
    'decimal',
  ],
  'Communication.payload.content[x]': ['string', 'Attachment', 'Reference'],
  'CommunicationRequest.occurrence[x]': ['dateTime', 'Period'],
  'CommunicationRequest.payload.content[x]': ['string', 'Attachment', 'Reference'],
  'Composition.relatesTo.target[x]': ['Identifier', 'Reference'],
  'ConceptMap.source[x]': ['uri', 'canonical'],
  'ConceptMap.target[x]': ['uri', 'canonical'],
  'Condition.abatement[x]': ['dateTime', 'Age', 'Period', 'Range', 'string'],
  'Condition.onset[x]': ['dateTime', 'Age', 'Period', 'Range', 'string'],
  'Consent.source[x]': ['Attachment', 'Reference'],
  'Contract.friendly.content[x]': ['Attachment', 'Reference'],
  'Contract.legal.content[x]': ['Attachment', 'Reference'],
  'Contract.legallyBinding[x]': ['Attachment', 'Reference'],
  'Contract.rule.content[x]': ['Attachment', 'Reference'],
  'Contract.term.action.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'Contract.term.asset.valuedItem.entity[x]': ['CodeableConcept', 'Reference'],
  'Contract.term.offer.answer.value[x]': [
    'boolean',
    'decimal',
    'integer',
    'date',
    'dateTime',
    'time',
    'string',
    'uri',
    'Attachment',
    'Coding',
    'Quantity',
    'Reference',
  ],
  'Contract.term.topic[x]': ['CodeableConcept', 'Reference'],
  'Contract.topic[x]': ['CodeableConcept', 'Reference'],
  'Coverage.costToBeneficiary.value[x]': ['SimpleQuantity', 'Money'],
  'CoverageEligibilityRequest.item.diagnosis.diagnosis[x]': ['CodeableConcept', 'Reference'],
  'CoverageEligibilityRequest.serviced[x]': ['date', 'Period'],
  'CoverageEligibilityResponse.insurance.item.benefit.allowed[x]': [
    'unsignedInt',
    'string',
    'Money',
  ],
  'CoverageEligibilityResponse.insurance.item.benefit.used[x]': ['unsignedInt', 'string', 'Money'],
  'CoverageEligibilityResponse.serviced[x]': ['date', 'Period'],
  'DataRequirement.dateFilter.value[x]': ['dateTime', 'Period', 'Duration'],
  'DataRequirement.subject[x]': ['CodeableConcept', 'Reference'],
  'DetectedIssue.identified[x]': ['dateTime', 'Period'],
  'DeviceDefinition.manufacturer[x]': ['string', 'Reference'],
  'DeviceRequest.code[x]': ['Reference', 'CodeableConcept'],
  'DeviceRequest.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'DeviceRequest.parameter.value[x]': ['CodeableConcept', 'Quantity', 'Range', 'boolean'],
  'DeviceUseStatement.timing[x]': ['Timing', 'Period', 'dateTime'],
  'DiagnosticReport.effective[x]': ['dateTime', 'Period'],
  'Dosage.asNeeded[x]': ['boolean', 'CodeableConcept'],
  'Dosage.doseAndRate.dose[x]': ['Range', 'SimpleQuantity'],
  'Dosage.doseAndRate.rate[x]': ['Ratio', 'Range', 'SimpleQuantity'],
  'EventDefinition.subject[x]': ['CodeableConcept', 'Reference'],
  'EvidenceVariable.characteristic.definition[x]': [
    'Reference',
    'canonical',
    'CodeableConcept',
    'Expression',
    'DataRequirement',
    'TriggerDefinition',
  ],
  'EvidenceVariable.characteristic.participantEffective[x]': [
    'dateTime',
    'Period',
    'Duration',
    'Timing',
  ],
  'ExplanationOfBenefit.accident.location[x]': ['Address', 'Reference'],
  'ExplanationOfBenefit.addItem.location[x]': ['CodeableConcept', 'Address', 'Reference'],
  'ExplanationOfBenefit.addItem.serviced[x]': ['date', 'Period'],
  'ExplanationOfBenefit.benefitBalance.financial.allowed[x]': ['unsignedInt', 'string', 'Money'],
  'ExplanationOfBenefit.benefitBalance.financial.used[x]': ['unsignedInt', 'Money'],
  'ExplanationOfBenefit.diagnosis.diagnosis[x]': ['CodeableConcept', 'Reference'],
  'ExplanationOfBenefit.item.location[x]': ['CodeableConcept', 'Address', 'Reference'],
  'ExplanationOfBenefit.item.serviced[x]': ['date', 'Period'],
  'ExplanationOfBenefit.procedure.procedure[x]': ['CodeableConcept', 'Reference'],
  'ExplanationOfBenefit.supportingInfo.timing[x]': ['date', 'Period'],
  'ExplanationOfBenefit.supportingInfo.value[x]': [
    'boolean',
    'string',
    'Quantity',
    'Attachment',
    'Reference',
  ],
  'FamilyMemberHistory.age[x]': ['Age', 'Range', 'string'],
  'FamilyMemberHistory.born[x]': ['Period', 'date', 'string'],
  'FamilyMemberHistory.condition.onset[x]': ['Age', 'Range', 'Period', 'string'],
  'FamilyMemberHistory.deceased[x]': ['boolean', 'Age', 'Range', 'date', 'string'],
  'Goal.start[x]': ['date', 'CodeableConcept'],
  'Goal.target.detail[x]': [
    'Quantity',
    'Range',
    'CodeableConcept',
    'string',
    'boolean',
    'integer',
    'Ratio',
  ],
  'Goal.target.due[x]': ['date', 'Duration'],
  'Group.characteristic.value[x]': ['CodeableConcept', 'boolean', 'Quantity', 'Range', 'Reference'],
  'GuidanceResponse.module[x]': ['uri', 'canonical', 'CodeableConcept'],
  'Immunization.occurrence[x]': ['dateTime', 'string'],
  'Immunization.protocolApplied.doseNumber[x]': ['positiveInt', 'string'],
  'Immunization.protocolApplied.seriesDoses[x]': ['positiveInt', 'string'],
  'ImmunizationEvaluation.doseNumber[x]': ['positiveInt', 'string'],
  'ImmunizationEvaluation.seriesDoses[x]': ['positiveInt', 'string'],
  'ImmunizationRecommendation.recommendation.doseNumber[x]': ['positiveInt', 'string'],
  'ImmunizationRecommendation.recommendation.seriesDoses[x]': ['positiveInt', 'string'],
  'ImplementationGuide.definition.page.name[x]': ['url', 'Reference'],
  'ImplementationGuide.definition.resource.example[x]': ['boolean', 'canonical'],
  'ImplementationGuide.manifest.resource.example[x]': ['boolean', 'canonical'],
  'Invoice.lineItem.chargeItem[x]': ['Reference', 'CodeableConcept'],
  'Library.subject[x]': ['CodeableConcept', 'Reference'],
  'Measure.subject[x]': ['CodeableConcept', 'Reference'],
  'Media.created[x]': ['dateTime', 'Period'],
  'Medication.ingredient.item[x]': ['CodeableConcept', 'Reference'],
  'MedicationAdministration.dosage.rate[x]': ['Ratio', 'SimpleQuantity'],
  'MedicationAdministration.effective[x]': ['dateTime', 'Period'],
  'MedicationAdministration.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicationDispense.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicationDispense.statusReason[x]': ['CodeableConcept', 'Reference'],
  'MedicationKnowledge.administrationGuidelines.indication[x]': ['CodeableConcept', 'Reference'],
  'MedicationKnowledge.administrationGuidelines.patientCharacteristics.characteristic[x]': [
    'CodeableConcept',
    'SimpleQuantity',
  ],
  'MedicationKnowledge.drugCharacteristic.value[x]': [
    'CodeableConcept',
    'string',
    'SimpleQuantity',
    'base64Binary',
  ],
  'MedicationKnowledge.ingredient.item[x]': ['CodeableConcept', 'Reference'],
  'MedicationRequest.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicationRequest.reported[x]': ['boolean', 'Reference'],
  'MedicationRequest.substitution.allowed[x]': ['boolean', 'CodeableConcept'],
  'MedicationStatement.effective[x]': ['dateTime', 'Period'],
  'MedicationStatement.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicinalProduct.specialDesignation.indication[x]': ['CodeableConcept', 'Reference'],
  'MedicinalProductAuthorization.procedure.date[x]': ['Period', 'dateTime'],
  'MedicinalProductContraindication.otherTherapy.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicinalProductIndication.otherTherapy.medication[x]': ['CodeableConcept', 'Reference'],
  'MedicinalProductInteraction.interactant.item[x]': ['Reference', 'CodeableConcept'],
  'MessageDefinition.event[x]': ['Coding', 'uri'],
  'MessageHeader.event[x]': ['Coding', 'uri'],
  'NutritionOrder.enteralFormula.administration.rate[x]': ['SimpleQuantity', 'Ratio'],
  'Observation.component.value[x]': [
    'Quantity',
    'CodeableConcept',
    'string',
    'boolean',
    'integer',
    'Range',
    'Ratio',
    'SampledData',
    'time',
    'dateTime',
    'Period',
  ],
  'Observation.effective[x]': ['dateTime', 'Period', 'Timing', 'instant'],
  'Observation.value[x]': [
    'Quantity',
    'CodeableConcept',
    'string',
    'boolean',
    'integer',
    'Range',
    'Ratio',
    'SampledData',
    'time',
    'dateTime',
    'Period',
  ],
  'Patient.deceased[x]': ['boolean', 'dateTime'],
  'Patient.multipleBirth[x]': ['boolean', 'integer'],
  'PlanDefinition.action.definition[x]': ['canonical', 'uri'],
  'PlanDefinition.action.relatedAction.offset[x]': ['Duration', 'Range'],
  'PlanDefinition.action.subject[x]': ['CodeableConcept', 'Reference'],
  'PlanDefinition.action.timing[x]': ['dateTime', 'Age', 'Period', 'Duration', 'Range', 'Timing'],
  'PlanDefinition.goal.target.detail[x]': ['Quantity', 'Range', 'CodeableConcept'],
  'PlanDefinition.subject[x]': ['CodeableConcept', 'Reference'],
  'Population.age[x]': ['Range', 'CodeableConcept'],
  'Procedure.performed[x]': ['dateTime', 'Period', 'string', 'Age', 'Range'],
  'Provenance.occurred[x]': ['Period', 'dateTime'],
  'Questionnaire.item.answerOption.value[x]': [
    'integer',
    'date',
    'time',
    'string',
    'Coding',
    'Reference',
  ],
  'Questionnaire.item.enableWhen.answer[x]': [
    'boolean',
    'decimal',
    'integer',
    'date',
    'dateTime',
    'time',
    'string',
    'Coding',
    'Quantity',
    'Reference',
  ],
  'Questionnaire.item.initial.value[x]': [
    'boolean',
    'decimal',
    'integer',
    'date',
    'dateTime',
    'time',
    'string',
    'uri',
    'Attachment',
    'Coding',
    'Quantity',
    'Reference',
  ],
  'QuestionnaireResponse.item.answer.value[x]': [
    'boolean',
    'decimal',
    'integer',
    'date',
    'dateTime',
    'time',
    'string',
    'uri',
    'Attachment',
    'Coding',
    'Quantity',
    'Reference',
  ],
  'RequestGroup.action.relatedAction.offset[x]': ['Duration', 'Range'],
  'RequestGroup.action.timing[x]': ['dateTime', 'Age', 'Period', 'Duration', 'Range', 'Timing'],
  'ResearchDefinition.subject[x]': ['CodeableConcept', 'Reference'],
  'ResearchElementDefinition.characteristic.definition[x]': [
    'CodeableConcept',
    'canonical',
    'Expression',
    'DataRequirement',
  ],
  'ResearchElementDefinition.characteristic.participantEffective[x]': [
    'dateTime',
    'Period',
    'Duration',
    'Timing',
  ],
  'ResearchElementDefinition.characteristic.studyEffective[x]': [
    'dateTime',
    'Period',
    'Duration',
    'Timing',
  ],
  'ResearchElementDefinition.subject[x]': ['CodeableConcept', 'Reference'],
  'RiskAssessment.occurrence[x]': ['dateTime', 'Period'],
  'RiskAssessment.prediction.probability[x]': ['decimal', 'Range'],
  'RiskAssessment.prediction.when[x]': ['Period', 'Range'],
  'ServiceRequest.asNeeded[x]': ['boolean', 'CodeableConcept'],
  'ServiceRequest.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'ServiceRequest.quantity[x]': ['Quantity', 'Ratio', 'Range'],
  'Specimen.collection.collected[x]': ['dateTime', 'Period'],
  'Specimen.collection.fastingStatus[x]': ['CodeableConcept', 'Duration'],
  'Specimen.container.additive[x]': ['CodeableConcept', 'Reference'],
  'Specimen.processing.time[x]': ['dateTime', 'Period'],
  'SpecimenDefinition.typeTested.container.additive.additive[x]': ['CodeableConcept', 'Reference'],
  'SpecimenDefinition.typeTested.container.minimumVolume[x]': ['SimpleQuantity', 'string'],
  'StructureMap.group.rule.source.defaultValue[x]': ['*'],
  'StructureMap.group.rule.target.parameter.value[x]': [
    'id',
    'string',
    'boolean',
    'integer',
    'decimal',
  ],
  'Substance.ingredient.substance[x]': ['CodeableConcept', 'Reference'],
  'SubstanceAmount.amount[x]': ['Quantity', 'Range', 'string'],
  'SubstanceReferenceInformation.target.amount[x]': ['Quantity', 'Range', 'string'],
  'SubstanceSpecification.moiety.amount[x]': ['Quantity', 'string'],
  'SubstanceSpecification.property.amount[x]': ['Quantity', 'string'],
  'SubstanceSpecification.property.definingSubstance[x]': ['Reference', 'CodeableConcept'],
  'SubstanceSpecification.relationship.amount[x]': ['Quantity', 'Range', 'Ratio', 'string'],
  'SubstanceSpecification.relationship.substance[x]': ['Reference', 'CodeableConcept'],
  'SupplyDelivery.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'SupplyDelivery.suppliedItem.item[x]': ['CodeableConcept', 'Reference'],
  'SupplyRequest.item[x]': ['CodeableConcept', 'Reference'],
  'SupplyRequest.occurrence[x]': ['dateTime', 'Period', 'Timing'],
  'SupplyRequest.parameter.value[x]': ['CodeableConcept', 'Quantity', 'Range', 'boolean'],
  'Task.input.value[x]': ['*'],
  'Task.output.value[x]': ['*'],
  'Timing.repeat.bounds[x]': ['Duration', 'Range', 'Period'],
  'TriggerDefinition.timing[x]': ['Timing', 'Reference', 'date', 'dateTime'],
  'UsageContext.value[x]': ['CodeableConcept', 'Quantity', 'Range', 'Reference'],
  'ValueSet.expansion.parameter.value[x]': [
    'string',
    'boolean',
    'integer',
    'decimal',
    'uri',
    'code',
    'dateTime',
  ],
} as const
type FhirR4ChoiceElements = typeof FhirR4ChoiceElements

export default FhirR4ChoiceElements
