import type { DateTime } from 'effect'
import { Effect, Layer, pipe } from 'effect'
import { HttpClient } from '@effect/platform/HttpClient'
import { UnhandledError } from '@assessmentis/ontology'
import type {
  ClinicalDataRepository,
  ClinicalDataRepositoryErrors,
} from '@assessmentis/clinical-domain'
import { Observation } from '@assessmentis/clinical-domain'
import {
  CodeableConcept,
  Coding,
  Code,
  IdentifierAndReference,
} from '@assessmentis/clinical-domain/data-types'
import { ObservationRepository } from '@assessmentis/clinical-domain/repositories'
import { DailyCoContext } from '@assessmentis/config-domain'
import { ApiDailyCoTranscriptSchema } from '../models/ApiDailyCoTranscriptSchema'
import { ApiDailyCoTranscriptLinkSchema } from '../models/ApiDailyCoTranscriptLinkSchema'
import {
  getRequestFromHeaders,
  handleHttpClientError,
  handle404,
  assertStatus,
  parseAs,
} from '../httpHelpers'

const TRANSCRIPT_OBSERVATION_CODE = CodeableConcept.make({
  coding: [
    Coding.Coding.make({
      system: 'http://assessment.is/fhir/observation-type',
      code: Code.make('video-call-transcript'),
      display: 'Video Call Transcript',
    }),
  ],
})

/**
 * Result of listing transcripts that includes the room name.
 */
export interface TranscriptObservationWithRoomName {
  readonly observation: Observation
  readonly roomName: string
}

/**
 * Fetch the access link for a transcript.
 */
const fetchTranscriptAccessLink = (
  httpClient: HttpClient,
  baseUrl: string,
  headersEffect: Effect.Effect<Record<string, string>, ClinicalDataRepositoryErrors>,
  transcriptId: string
): Effect.Effect<
  string | undefined,
  ClinicalDataRepositoryErrors
> =>
  pipe(
    headersEffect,
    getRequestFromHeaders(
      httpClient,
      new URL(`${baseUrl}/transcript/${transcriptId}/access-link`),
      {}
    ),
    handleHttpClientError(
      'HTTP Client Error while fetching transcript link'
    ),
    handle404('Transcript', { url: `${baseUrl}/transcript/${transcriptId}` }),
    assertStatus(200),
    parseAs(ApiDailyCoTranscriptLinkSchema),
    Effect.map((linkData) => linkData.link),
    Effect.catchTag('NotFoundError', () => Effect.succeed(undefined))
  )

/**
 * Build an Observation from a Daily.co transcript.
 *
 * Uses valueString for the transcript access link (the actual text content
 * would be fetched by the consumer). derivedFrom can be set by the consumer
 * to reference the Media (recording) this transcript was derived from.
 */
const transcriptToObservation = (transcript: {
  transcriptId: string
  accessLink: string
  duration?: number
}): Observation =>
  Observation.make({
    status: 'final' as const,
    code: TRANSCRIPT_OBSERVATION_CODE,
    valueString: transcript.accessLink,
    identifier: [
      IdentifierAndReference.Identifier.make({
        system: 'http://assessment.is/fhir/daily-co-transcript-id',
        value: transcript.transcriptId,
      }),
    ],
  })

/**
 * Implementation of ClinicalDataRepository<Observation> backed by the
 * Daily.co Transcripts API.
 *
 * This repository is read-only — transcripts are generated by Daily.co
 * during recorded video calls.
 */
export const makeDailyCoTranscriptObservationRepository = (
  httpClient: HttpClient,
  baseUrl: string,
  headersEffect: Effect.Effect<
    Record<string, string>,
    ClinicalDataRepositoryErrors
  >
): ClinicalDataRepository<Observation> & {
  /**
   * List all transcripts with pagination, returning room names alongside Observations.
   */
  listAllTranscriptsWithRoomName: (
    sinceTimestamp?: DateTime.Utc
  ) => Effect.Effect<
    TranscriptObservationWithRoomName[],
    ClinicalDataRepositoryErrors
  >
} => ({
  get: () =>
    Effect.fail(
      new UnhandledError({
        message:
          'Daily.co transcripts cannot be fetched by ID. Use getMany or listAllTranscriptsWithRoomName.',
      })
    ),

  getMany: () =>
    Effect.fail(
      new UnhandledError({
        message:
          'Daily.co transcript listing requires pagination. Use listAllTranscriptsWithRoomName instead.',
      })
    ),

  create: () =>
    Effect.fail(
      new UnhandledError({
        message: 'Daily.co transcripts are read-only and cannot be created via this repository',
      })
    ),

  createMany: () =>
    Effect.fail(
      new UnhandledError({
        message: 'Daily.co transcripts are read-only and cannot be created via this repository',
      })
    ),

  update: () =>
    Effect.fail(
      new UnhandledError({
        message: 'Daily.co transcripts are read-only and cannot be updated via this repository',
      })
    ),

  delete: () =>
    Effect.fail(
      new UnhandledError({
        message: 'Daily.co transcripts are read-only and cannot be deleted via this repository',
      })
    ),

  listAllTranscriptsWithRoomName: (sinceTimestamp?: DateTime.Utc) =>
    Effect.gen(function* () {
      const allTranscripts: TranscriptObservationWithRoomName[] = []
      let cursor: string | undefined = sinceTimestamp?.epochMillis
        ? String(sinceTimestamp)
        : undefined

      let hasMore = true
      while (hasMore) {
        const url = new URL(`${baseUrl}/transcript`)
        url.searchParams.set('limit', '100')
        if (cursor) {
          url.searchParams.set('starting_after', cursor)
        }

        const page = yield* pipe(
          headersEffect,
          getRequestFromHeaders(httpClient, url, {}),
          handleHttpClientError('Error while listing all transcripts'),
          assertStatus(200),
          parseAs(ApiDailyCoTranscriptSchema)
        )

        for (const transcript of page.data) {
          if (transcript.status !== 'transcribed') continue

          const accessLink = yield* fetchTranscriptAccessLink(
            httpClient,
            baseUrl,
            headersEffect,
            transcript.transcriptId
          )
          if (!accessLink) continue

          const roomName = transcript.roomName
          if (!roomName) continue

          const observation = transcriptToObservation({
            transcriptId: transcript.transcriptId,
            accessLink,
            duration: transcript.duration,
          })
          allTranscripts.push({ observation, roomName })
        }

        if (page.data.length < 100) {
          hasMore = false
        } else {
          const lastTranscript = page.data[page.data.length - 1]!
          cursor = lastTranscript.transcriptId
        }
      }

      return allTranscripts
    }),
})

/**
 * Layer providing ObservationRepository backed by Daily.co transcripts API.
 */
export const DailyCoTranscriptObservationLayer: Layer.Layer<
  ObservationRepository,
  never,
  HttpClient | DailyCoContext
> = Layer.effect(
  ObservationRepository,
  Effect.gen(function* () {
    const httpClient = yield* HttpClient
    const { config: dailyCoConf, authHeadersEffect: headersEffect } =
      yield* DailyCoContext
    const baseUrl =
      typeof window === 'undefined'
        ? 'https://api.daily.co/v1'
        : dailyCoConf.dailyCoProxyUrl

    return makeDailyCoTranscriptObservationRepository(
      httpClient,
      baseUrl,
      headersEffect
    )
  })
)
