import './implementations/composition'
import './implementations/encounter'
import './implementations/location'
import './implementations/observation'
import './implementations/patient'
import './implementations/practitioner'
import './implementations/questionnaire'
import './implementations/questionnaire-response'
export * from './apply-labeled'
export * from './labeled'
