name: Lint

on: pull_request

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          NODE_ENV=development npm ci --include=dev
          npm ci --workspaces

      - name: Lint apps/frontend
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: apps/frontend
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context

      - name: Lint apps/functions
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: apps/functions

      - name: Lint apps/aws_infra
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: apps/aws_infra

      - name: Lint domain/clinical-domain
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: domain/clinical-domain

      - name: Lint domain/platform-domain
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: domain/platform-domain

      - name: Lint domain/questionnaire-domain
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: domain/questionnaire-domain

      - name: Lint domain/video-call-domain
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: domain/video-call-domain

      - name: Lint domain/document-domain
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: domain/document-domain

      - name: Lint global/react-util
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: global/react-util

      - name: Lint global/util
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: global/util

      - name: Lint global/ontology
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: global/ontology

      - name: Lint infrastructure/daily-co-infrastructure
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/daily-co-infrastructure

      - name: Lint infrastructure/firebase-web-infrastructure
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/firebase-web-infrastructure

      - name: Lint infrastructure/google-fhir-web-infrastructure
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/google-fhir-web-infrastructure

      - name: Lint infrastructure/google-meet-infrastructure
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/google-meet-infrastructure

      - name: Lint infrastructure/firebase-server-infrastructure
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/firebase-server-infrastructure

      - name: Lint infrastructure/document-template-instances
        uses: reviewdog/action-eslint@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
          workdir: infrastructure/document-template-instances

# -
# -
# -
# -
# -
# -
# -
# -
# -
# -
