name: Lint changed files

on: pull_request

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint-changed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: frontend
            working-directory: apps/frontend
          - name: functions
            working-directory: apps/functions
          - name: clinical-domain
            working-directory: domain/clinical-domain
          - name: config-domain
            working-directory: domain/config-domain
          - name: platform-domain
            working-directory: domain/platform-domain
          - name: react-util
            working-directory: global/react-util
          - name: util
            working-directory: global/util
          - name: daily-co-infrastructure
            working-directory: domain/daily-co-infrastructure
          - name: firebase-web-infrastructure
            working-directory: infrastructure/firebase-web-infrastructure
          - name: google-fhir-infrastructure
            working-directory: infrastructure/google-fhir-infrastructure
          - name: google-meet-infrastructure
            working-directory: infrastructure/google-meet-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ESLint with reviewdog on changed files
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: ${{ matrix.working-directory }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: diff_context
